Repository cloudposse/atmos, pull requests merged in 2021-11, with the labels that each got.

#67 Update `auto-release.yml`
  .github/auto-release.yml
Labels: patch

#68 Update stack processor
  Makefile
  internal/config/utils.go
  pkg/component/component_processor.go
  pkg/stack/stack_processor.go
  pkg/stack/stack_processor_utils.go
Labels: patch

#69 Move packages from `internal` to `pkg` folder
  go.mod
  internal/exec/describe.go
  internal/exec/helmfile.go
  internal/exec/terraform.go
  internal/exec/terraform_generate.go
  internal/exec/utils.go
  pkg/component/component_processor.go
  pkg/config/config.go
  pkg/config/schema.go
  pkg/config/utils.go
  pkg/globals/globals.go
  pkg/stack/stack_processor.go
  pkg/stack/stack_processor_utils.go
Labels: patch

#71 Add `--from-plan` flag to terraform apply/deploy commands. Add `describe config` CLI command
  Makefile
  cmd/describe.go
  cmd/describe_config.go
  go.mod
  go.sum
  internal/exec/describe.go
  internal/exec/terraform.go
  internal/exec/utils.go
  main.go
  pkg/config/schema.go
  pkg/config/utils.go
  pkg/globals/globals.go
  pkg/stack/stack_processor.go
  pkg/stack/stack_processor_utils.go
Labels: patch

#73 Fix `terraform import` command. Add `terraform clean` command. Update spacelift processor
  internal/exec/helmfile.go
  internal/exec/terraform.go
  internal/exec/utils.go
  pkg/config/config.go
  pkg/config/utils.go
  pkg/spacelift/atmos.yaml
  pkg/spacelift/spacelift_stack_processor.go
  pkg/spacelift/spacelift_stack_processor_test.go
Labels: patch

#75 Run `terraform init -reconfigure` when running `terraform workspace`. Fix infrastructure stack name in Spacelift processor
  internal/exec/terraform.go
  pkg/spacelift/spacelift_stack_processor.go
  pkg/spacelift/spacelift_stack_processor_test.go
Labels: patch

#76 Update remote state backend. Add acceptance tests
  .github/workflows/build.yml
  .github/workflows/test.yml
  Makefile
  examples/complete/rootfs/usr/local/etc/atmos/atmos.yaml
  examples/complete/stacks/catalog/terraform/test-component.yaml
  examples/complete/stacks/catalog/terraform/top-level-component1.yaml
  examples/complete/stacks/catalog/terraform/vpc.yaml
  examples/complete/stacks/globals/globals.yaml
  pkg/stack/stack_processor.go
  pkg/stack/stack_processor_test.go
Labels: patch

#77 Detect ENV vars in YAML stack config and set them for command execution. Make `workspace_key_prefix` config DRY
  examples/complete/stacks/catalog/terraform/test-component-override.yaml
  examples/complete/stacks/catalog/terraform/test-component.yaml
  examples/complete/stacks/catalog/terraform/top-level-component1.yaml
  internal/exec/describe.go
  internal/exec/helmfile.go
  internal/exec/terraform.go
  internal/exec/terraform_generate.go
  internal/exec/utils.go
  pkg/config/schema.go
  pkg/stack/stack_processor.go
  pkg/stack/stack_processor_test.go
Labels: patch

#78 Change misspelled error messages
  internal/exec/helmfile.go
  internal/exec/terraform.go
Labels: bugfix

#80 Add install instructions
  README.yaml
Labels: no-release

#81 New actions to bump homebrew and auto format action
  .github/workflows/auto-format.yml
  .github/workflows/build.yml
  README.md
  README.yaml
Labels: no-release
