Repository cloudposse/atmos, pull requests merged in 2022-05, with the labels that each got.

#145 Add `atmos vendor` commands. Add `atmos vendor pull` command. Improve error messages. Cleanup code
  cmd/vendor.go
  cmd/vendor_pull.go
  cmd/workflow.go
  examples/complete/Dockerfile
  examples/complete/components/terraform/infra/vpc-flow-logs-bucket/component.yaml
  go.mod
  go.sum
  internal/exec/describe_component.go
  internal/exec/helmfile.go
  internal/exec/helmfile_generate_varfile.go
  internal/exec/help.go
  internal/exec/shell_utils.go
  internal/exec/terraform.go
  internal/exec/terraform_generate_backend.go
  internal/exec/terraform_generate_varfile.go
  internal/exec/utils.go
  internal/exec/vendor.go
  internal/exec/vendor_utils.go
  internal/exec/worflow.go
  pkg/config/config.go
  pkg/config/schema.go
  pkg/config/utils.go
  pkg/stack/stack_processor.go
  pkg/utils/os_utils.go
  pkg/vender/atmos.yaml
  pkg/vender/component_vendor_test.go
Labels: patch

#144 git.io->cloudposse.tools update
  Makefile
Labels: no-release

#146 Improve error handling and error messages. Add `atmos validate stacks` command
  cmd/validate.go
  cmd/validate_stacks.go
  cmd/vendor_diff.go
  cmd/vendor_pull.go
  examples/complete/stacks/catalog/invalid-yaml/invalid-yaml-1.yaml
  examples/complete/stacks/catalog/invalid-yaml/invalid-yaml-2.yaml
  examples/complete/stacks/catalog/invalid-yaml/invalid-yaml-3.yaml
  examples/complete/stacks/catalog/invalid-yaml/invalid-yaml-4.yaml
  examples/complete/stacks/catalog/invalid-yaml/invalid-yaml-5.yaml
  examples/complete/stacks/catalog/invalid-yaml/invalid-yaml-6.yaml
  examples/complete/stacks/catalog/invalid-yaml/invalid-yaml-7.yaml
  internal/exec/validate_stacks.go
  pkg/config/config.go
  pkg/config/utils.go
  pkg/stack/stack_processor.go
  pkg/stack/stack_processor_utils.go
  pkg/validate/atmos.yaml
  pkg/validate/validate_stacks_test.go
  pkg/vender/component_vendor_test.go
Labels: patch

#147 Support terraform two-words commands
  internal/exec/helmfile.go
  internal/exec/helmfile_generate_varfile.go
  internal/exec/shell_utils.go
  internal/exec/terraform.go
  internal/exec/terraform_generate_varfile.go
  internal/exec/utils.go
  pkg/config/schema.go
Labels: patch

#149 Various fixes and improvements. Better error messages. Improve `validate stacks` and `describe stacks` commands
  atmos.yaml
  examples/complete/Dockerfile
  examples/complete/atmos.yaml
  examples/complete/rootfs/usr/local/etc/atmos/atmos.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-import-1.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-import-2.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-import-3.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-import-4.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-import-5.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-import-6.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-import-7.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-import-8.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-import-9.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-1.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-10.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-11.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-12.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-13.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-14.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-15.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-2.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-3.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-4.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-5.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-6.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-7.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-8.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-schema-9.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-yaml-1.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-yaml-2.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-yaml-3.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-yaml-4.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-yaml-5.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-yaml-6.yaml
  examples/complete/stacks/catalog/invalid-yaml-and-schema/invalid-yaml-7.yaml
  examples/complete/stacks/catalog/terraform/test-component-override-3.yaml
  examples/complete/stacks/catalog/terraform/test-component-override.yaml
  internal/exec/describe_stacks.go
  internal/exec/helmfile.go
  internal/exec/terraform.go
  internal/exec/utils.go
  internal/exec/validate_stacks.go
  pkg/component/atmos.yaml
  pkg/config/config.go
  pkg/spacelift/atmos.yaml
  pkg/spacelift/spacelift_stack_processor.go
  pkg/spacelift/spacelift_stack_processor_test.go
  pkg/stack/stack_processor.go
  pkg/stack/stack_processor_test.go
  pkg/stack/stack_processor_utils.go
  pkg/validate/atmos.yaml
  pkg/vender/atmos.yaml
  website/docs/cli/configuration.md
  website/package-lock.json
  website/package.json
Labels: patch

#150 Support `{attributes}` token in the `components.helmfile.cluster_name_pattern` CLI config
  pkg/aws/atmos.yaml
  pkg/aws/aws_eks_update_kubeconfig_test.go
  pkg/config/schema.go
  pkg/config/utils.go
  website/package-lock.json
  website/package.json
Labels: patch

#151 Improve `atmos vendor pull` command. Add more vendoring examples and tests
  examples/complete/Dockerfile
  examples/complete/components/terraform/infra/account-map/component.yaml
  examples/complete/components/terraform/infra/vpc-flow-logs-bucket/component.yaml
  internal/exec/vendor_utils.go
  pkg/vender/component_vendor_test.go
Labels: patch

#153 Update `atmos workflow` command
  cmd/workflow.go
  examples/complete/workflows/workflow1.yaml
  internal/exec/worflow.go
  internal/exec/worflow_utils.go
Labels: patch

#152 Add GitHub Actions to deploy release to prod, PRs to preview environments, and destroy preview environments
  .github/workflows/website-deploy-preview.yml
  .github/workflows/website-deploy-release.yml
  .github/workflows/website-destroy-preview.yml
  website/.nvmrc
  website/package-lock.json
  website/package.json
Labels: patch, no-release

#154 README: Fix spacing, add console highlight
  README.md
  README.yaml
Labels: no-release
