Repository cloudposse/atmos, pull requests merged in 2024-12, with the labels that each got.

#721 fix: Cut release only when all tests passed
  .github/workflows/test.yml
Labels: no-release

#827 Export configuration information in shell launched by Atmos
  internal/exec/shell_utils.go
  website/docs/cli/configuration/configuration.mdx
  website/docs/quick-start/install-atmos.mdx
Labels: minor

#839 Fix preview deployment
  .github/workflows/website-preview-deploy.yml
Labels: no-release

#862 Mergify
  .github/CODEOWNERS
  .github/mergify.yml
  .github/workflows/test.yml
  examples/tests/atmos.yaml
Labels: no-release

#865 atmos read/write storage interface
  go.mod
  go.sum
  internal/exec/yaml_func_exec.go
  internal/exec/yaml_func_store.go
  internal/exec/yaml_func_template.go
  internal/exec/yaml_func_terraform_output.go
  internal/exec/yaml_func_utils.go
  pkg/config/config.go
  pkg/config/utils.go
  pkg/hooks/hooks.go
  pkg/schema/schema.go
  pkg/store/aws_ssm_param_store.go
  pkg/store/aws_ssm_param_store_test.go
  pkg/store/config.go
  pkg/store/in_memory_store.go
  pkg/store/in_memory_store_test.go
  pkg/store/registry.go
  pkg/store/store.go
  pkg/utils/yaml_utils.go
Labels: no-release, needs-cloudposse

#869 refactor loading and checking of atmos config
  cmd/atlantis_generate_repo_config.go
  cmd/cmd_utils.go
  cmd/describe_affected.go
  cmd/describe_component.go
  cmd/describe_dependents.go
  cmd/describe_stacks.go
  cmd/helmfile.go
  cmd/helmfile_generate_varfile.go
  cmd/list_components.go
  cmd/list_stacks.go
  cmd/pro_lock.go
  cmd/pro_unlock.go
  cmd/root.go
  cmd/terraform.go
  cmd/terraform_generate_backend.go
  cmd/terraform_generate_backends.go
  cmd/terraform_generate_varfile.go
  cmd/terraform_generate_varfiles.go
  cmd/validate_component.go
  cmd/validate_stacks.go
  cmd/vendor_diff.go
  cmd/vendor_pull.go
  cmd/version.go
  go.sum
Labels: no-release

#885 revert "refactor loading and checking of atmos config"
  cmd/atlantis_generate_repo_config.go
  cmd/cmd_utils.go
  cmd/describe_affected.go
  cmd/describe_component.go
  cmd/describe_dependents.go
  cmd/describe_stacks.go
  cmd/helmfile.go
  cmd/helmfile_generate_varfile.go
  cmd/list_components.go
  cmd/list_stacks.go
  cmd/pro_lock.go
  cmd/pro_unlock.go
  cmd/root.go
  cmd/terraform.go
  cmd/terraform_generate_backend.go
  cmd/terraform_generate_backends.go
  cmd/terraform_generate_varfile.go
  cmd/terraform_generate_varfiles.go
  cmd/validate_component.go
  cmd/validate_stacks.go
  cmd/vendor_diff.go
  cmd/vendor_pull.go
  cmd/version.go
  go.sum
Labels: no-release

#877 Fix Mocks for Windows
  .github/workflows/test.yml
  tests/cli_test.go
  tests/test_cases.yaml
Labels: no-release, needs-cloudposse

#890 Trigger workflows from github actions bot
  .github/mergify.yml
Labels: needs-cloudposse
