Repository cloudposse/atmos, pull requests merged in 2025-06, with the labels that each got.

#1278 DEV-3258: OIDC Token Exchange
  pkg/config/const.go
  pkg/pro/api_client.go
  pkg/pro/api_client_test.go
  pkg/pro/requests.go
Labels: minor, size/m

#1289 bug: fix oidc exchange
  cmd/pro.go
  internal/exec/describe_affected.go
  internal/exec/pro.go
  pkg/pro/api_client.go
  pkg/pro/api_client_exchange_oidc_token_test.go
  pkg/pro/api_client_get_github_oidc_token_test.go
  pkg/pro/api_client_lock_test.go
  pkg/pro/api_client_test.go
  pkg/pro/api_client_unlock_test.go
  pkg/pro/api_client_upload_affected_stacks_test.go
  pkg/pro/dtos/README.md
  pkg/pro/dtos/atmos_api_response.go
  pkg/pro/dtos/exchange_github_oidc_token.go
  pkg/pro/dtos/get_github_oidc_token.go
  pkg/pro/dtos/lock_stack.go
  pkg/pro/dtos/unlock_stack.go
  pkg/pro/dtos/upload_affected_stacks.go
  pkg/pro/requests.go
  tests/fixtures/scenarios/complete/atmos.yaml
  tests/fixtures/scenarios/complete/rootfs/usr/local/etc/atmos/atmos.yaml
  tests/fixtures/scenarios/editorconfig/atmos.yaml
  tests/snapshots/TestCLICommands_atmos_--help.stdout.golden
  tests/snapshots/TestCLICommands_check_atmos_--help_in_empty-dir.stdout.golden
  website/docs/cli/commands/pro/pro-lock.mdx
  website/docs/cli/commands/pro/pro-unlock.mdx
Labels: minor, size/xl

#1290 debugging atmos pro oidc exchange
  internal/exec/describe_affected.go
  pkg/pro/api_client.go
  pkg/pro/api_client_test.go
  pkg/pro/api_client_upload_affected_stacks_test.go
Labels: minor, size/s

#1239 chore: Screengrabs
  .github/workflows/screengrabs.yaml
  demo/screengrabs/Makefile
  demo/screengrabs/build-all.sh
  demo/screengrabs/scripts/demo-stacks/.demo.rc
Labels: no-release, needs-cloudposse, size/m

#1297 Added feature-release environment
  .github/settings.yml
Labels: no-release, needs-cloudposse, size/xs

#1353 Go releaser config support draft mode
  .github/workflows/test.yml
  .goreleaser.yml
Labels: patch, needs-cloudposse, size/s
