Repository cloudposse/atmos, pull requests merged in 2025-02, with the labels that each got.

#1007 deprecate in memory store
  .vscode/settings.json
  pkg/store/in_memory_store.go
  pkg/store/in_memory_store_test.go
  pkg/store/registry.go
Labels: no-release, needs-cloudposse

#1008 add redis store
  go.mod
  go.sum
  pkg/store/redis_store.go
  pkg/store/redis_store_test.go
  pkg/store/registry.go
  pkg/store/store.go
  website/docs/core-concepts/projects/configuration/stores.mdx
Labels: no-release, needs-cloudposse

#1004 Running atmos docs (with no args) should emit message
  cmd/docs.go
  tests/snapshots/TestCLICommands_atmos_docs.stdout.golden
  tests/test-cases/core.yaml
Labels: no-release

#1005 feat: add spinner during `atmos validate stacks` operations
  internal/exec/validate_stacks.go
  tests/snapshots/TestCLICommands_atmos_validate_stacks_with_metadata.stdout.golden
Labels: no-release

#1017 update artifactory store to use getKey
  pkg/store/artifactory_store.go
Labels: no-release

#1011 update artifactory store to allow anonymous access
  pkg/store/artifactory_store.go
  website/docs/core-concepts/projects/configuration/stores.mdx
Labels: no-release

#1010 restore hooks functionality
  cmd/terraform.go
  cmd/terraform_commands.go
  go.mod
  go.sum
  main_test.go
  pkg/hooks/cmd.go
  pkg/hooks/command.go
  pkg/hooks/event.go
  pkg/hooks/hook.go
  pkg/hooks/hooks.go
  pkg/hooks/store.go
  pkg/hooks/store_cmd.go
  testdata/fixtures/hooks-test/atmos.yaml
  testdata/fixtures/hooks-test/components/terraform/random/main.tf
  testdata/fixtures/hooks-test/stacks/stack.yaml
Labels: no-release

#1002 Sanitize snapshots
  tests/cli_test.go
  tests/snapshots/TestCLICommands_atmos_describe_config.stdout.golden
  tests/snapshots/TestCLICommands_atmos_describe_config_-f_yaml.stdout.golden
  tests/test-cases/demo-stacks.yaml
Labels: no-release

#1021 move hook and store test
  main_test.go
  tests/fixtures/scenarios/hooks-test/atmos.yaml
  tests/fixtures/scenarios/hooks-test/components/terraform/hook-and-store/main.tf
  tests/fixtures/scenarios/hooks-test/stacks/stack.yaml
Labels: no-release

#1020 allow user to specify default value when using store
  internal/exec/yaml_func_store.go
  internal/exec/yaml_func_store_test.go
  website/docs/core-concepts/stacks/yaml-functions/store.mdx
Labels: no-release, minor

#1051 Add Test Timeouts and Clean Working & Home Directories
  tests/README.md
  tests/cli_test.go
  tests/snapshots/TestCLICommands_Valid_Log_Level_in_Config_File.stderr.golden
  tests/snapshots/TestCLICommands_Valid_Log_Level_in_Config_File.stdout.golden
  tests/snapshots/TestCLICommands_Valid_Log_Level_in_Environment_Variable.stderr.golden
  tests/snapshots/TestCLICommands_Valid_log_file_in_env_should_be_priortized_over_config.stdout.golden
  tests/snapshots/TestCLICommands_Valid_log_file_in_flag_should_be_priortized_over_env_and_config.stdout.golden
  tests/snapshots/TestCLICommands_Valid_log_level_in_env_should_be_priortized_over_config.stderr.golden
  tests/snapshots/TestCLICommands_Valid_log_level_in_env_should_be_priortized_over_config.stdout.golden
  tests/snapshots/TestCLICommands_Valid_log_level_in_flag_should_be_priortized_over_env_and_config.stderr.golden
  tests/snapshots/TestCLICommands_Valid_log_level_in_flag_should_be_priortized_over_env_and_config.stdout.golden
  tests/test-cases/help-and-usage.yaml
  tests/test-cases/log-level-validation.yaml
Labels: no-release

#1059 Fix mergify dispatch
  .github/mergify.yml
Labels: no-release, needs-cloudposse

#1063 Update Smoke Tests to Check for Stale Atmos Binary
  tests/cli_test.go
Labels: no-release, triage

#793 Document Atmos Development Conventions
  docs/help.md
  docs/logging.md
Labels: no-release

#1075 Add shared configuration for RunsOn GHA runners
  .github/runs-on.yml
Labels: no-release, needs-cloudposse

#1098 Implement PR Size Labeler
  .github/workflows/codeql.yml
Labels: no-release, needs-cloudposse, size/s

#1099 Use Mergify for PR Size Comments
  .github/mergify.yml
  .github/workflows/codeql.yml
Labels: no-release, needs-cloudposse, size/s
