Repository cloudposse/atmos, pull requests merged in 2025-08, with the labels that each got.

#1388 Support Spacelift CI provider in telemetry
  internal/exec/describe_affected_utils_2_test.go
  pkg/telemetry/ci.go
  pkg/telemetry/ci_test.go
Labels: patch, needs-cloudposse, size/m

#1421 Fix flaky Packer tests in GitHub Actions
  .github/workflows/test.yml
Labels: no-release, needs-cloudposse, size/xs

#1419 Add comprehensive CLAUDE.md development guide
  CLAUDE.md
Labels: no-release, size/l
