Repository cloudposse/atmos, pull requests merged in 2025-03, with the labels that each got.

#1101 Add Codecov to Report Test Coverage
  .github/workflows/test.yml
  .gitignore
  Makefile
  codecov.yml
Labels: no-release, needs-cloudposse, size/s

#1100 chore: remove github token
  .github/workflows/codeql.yml
Labels: no-release, needs-cloudposse, size/xs

#1113 fix formatting
  .github/workflows/test.yml
  cmd/helmfile_apply.go
  cmd/helmfile_destroy.go
  cmd/helmfile_diff.go
  cmd/helmfile_sync.go
  internal/exec/atlantis_utils.go
  internal/exec/config_sources_utils.go
  internal/exec/describe_workflows.go
  internal/exec/pro.go
  internal/exec/spacelift_utils.go
  internal/exec/stack_processor_utils.go
  internal/exec/validate_utils.go
  internal/exec/vendor.go
  pkg/list/list_workflows_test.go
  pkg/pro/api_client.go
  pkg/spacelift/spacelift_stack_processor_test.go
  pkg/stack/stack_processor_test.go
  pkg/store/artifactory_store_test.go
  pkg/utils/glob_utils.go
  pkg/utils/highlight_utils.go
  pkg/utils/version_utils.go
  pkg/vender/vendor_config_test.go
Labels: no-release, needs-cloudposse, size/s

#1112 fix store bug and allow for hooks at multiple levels of config
  internal/exec/stack_processor_utils.go
  pkg/store/artifactory_store_test.go
  pkg/store/aws_ssm_param_store.go
  pkg/store/aws_ssm_param_store_test.go
  pkg/store/redis_store_test.go
  tests/fixtures/scenarios/hooks-test/stacks/stack.yaml
  tests/fixtures/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json
  website/docs/core-concepts/stacks/hooks.mdx
  website/docs/core-concepts/stacks/overrides.mdx
Labels: patch, needs-cloudposse, size/l

#1117 Fix go releaser configs to support pre-releases
  .goreleaser.yml
Labels: no-release, size/xs

#1119 Tests should not inherit ENV
  tests/cli_test.go
Labels: no-release, size/s

#1116 fix store bug with non json values
  .github/workflows/build.yml
  .golangci.yml
  pkg/store/artifactory_store.go
  pkg/store/artifactory_store_test.go
  pkg/store/aws_ssm_param_store.go
  pkg/store/aws_ssm_param_store_test.go
  pkg/store/errors.go
  pkg/store/redis_store.go
  pkg/store/redis_store_test.go
  pkg/store/registry.go
  pkg/store/store.go
Labels: patch, needs-cloudposse, size/m

#1131 Warn on Excessive Function Returns & `//nolint` Usage
  .golangci.yml
Labels: size/xs

#1137 Use official `golangci` action together with CodeQL
  .github/mergify.yml
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  .golangci.yml
  Makefile
  internal/exec/terraform_utils.go
Labels: no-release, needs-cloudposse, size/m

#1138 Change the level and severity of `function-result-limit`
  .golangci.yml
Labels: no-release, size/xs

#1139 Fork go-homedir into Atmos
  go.mod
  pkg/config/config.go
  pkg/config/go-homedir/ATTRIBUTIONS.md
  pkg/config/go-homedir/LICENSE
  pkg/config/go-homedir/README.md
  pkg/config/go-homedir/homedir.go
  pkg/config/go-homedir/homedir_test.go
Labels: patch, size/m

#1093 Fix OCI Tests & Vendoring
  .gitignore
  .golangci.yml
  go.mod
  internal/exec/oci_utils.go
  internal/exec/tar_utils.go
  internal/exec/vendor.go
  internal/exec/vendor_component_utils.go
  internal/exec/vendor_model.go
  internal/exec/vendor_model_component.go
  internal/exec/vendor_utils.go
  internal/exec/vendor_utils_test.go
  pkg/vender/component_vendor_test.go
  pkg/vender/vendor_config_test.go
  tests/fixtures/components/upload-oci-components.sh
  tests/fixtures/scenarios/complete/components/terraform/infra/vpc2/component.yaml
  tests/fixtures/scenarios/complete/vendor.yaml
  tests/fixtures/scenarios/complete/vendor/vendor2.yaml
  tests/fixtures/scenarios/editorconfig/vendor.yaml
  tests/fixtures/scenarios/vendor/test-components/README.md
  tests/fixtures/scenarios/vendor/test-components/main.tf
  tests/fixtures/scenarios/vendor/test-components/outputs.tf
  tests/fixtures/scenarios/vendor/test-components/providers.tf
  tests/fixtures/scenarios/vendor/test-components/variables.tf
  tests/fixtures/scenarios/vendor/test-components/versions.tf
  tests/fixtures/scenarios/vendor/vendor.yaml
  tests/fixtures/scenarios/vendor/vendor/vendor2.yaml
  tests/test-cases/vendor-test.yaml
Labels: patch, size/xl

#1140 Lint check for dogsleds and duplicated code
  .golangci.yml
Labels: no-release, size/s

#1148 Fix snapshots extra slashes
  atmos.yaml
  tests/cli_terraform_test.go
  tests/cli_test.go
Labels: no-release, size/s

#1123 Update atmos schema
  internal/exec/validate_component.go
  internal/exec/validate_stacks.go
  pkg/config/config.go
  pkg/config/utils.go
  pkg/schema/schema.go
  pkg/schema/schema_test.go
  tests/snapshots/TestCLICommands_Valid_log_file_in_env_should_be_priortized_over_config.stdout.golden
  tests/snapshots/TestCLICommands_Valid_log_file_in_flag_should_be_priortized_over_env_and_config.stdout.golden
  tests/snapshots/TestCLICommands_Valid_log_level_in_flag_should_be_priortized_over_env_and_config.stderr.golden
  tests/snapshots/TestCLICommands_Valid_log_level_in_flag_should_be_priortized_over_env_and_config.stdout.golden
  tests/snapshots/TestCLICommands_atmos_describe_config.stdout.golden
Labels: patch, size/m

#1034 Google secret manager store implementation
  go.mod
  go.sum
  pkg/store/errors.go
  pkg/store/google_secret_manager_store.go
  pkg/store/google_secret_manager_store_test.go
  pkg/store/registry.go
  website/docs/core-concepts/projects/configuration/stores.mdx
Labels: minor

#1103 Remove unused flag code in root
  cmd/root.go
  cmd/terraform_generate_backend_test.go
  internal/exec/terraform_outputs.go
  pkg/config/config.go
  pkg/config/utils.go
  pkg/utils/log_utils.go
  tests/snapshots/TestCLICommands_Invalid_Log_Level_in_Environment_Variable.stderr.golden
  tests/snapshots/TestCLICommands_Valid_Log_Level_in_Command_Line_Flag.stdout.golden
  tests/snapshots/TestCLICommands_Valid_Log_Level_in_Config_File.stderr.golden
  tests/snapshots/TestCLICommands_Valid_Log_Level_in_Config_File.stdout.golden
  tests/snapshots/TestCLICommands_Valid_Log_Level_in_Environment_Variable.stderr.golden
  tests/snapshots/TestCLICommands_Valid_Log_Level_in_Environment_Variable.stdout.golden
  tests/snapshots/TestCLICommands_Valid_log_file_in_env_should_be_priortized_over_config.stdout.golden
  tests/snapshots/TestCLICommands_Valid_log_file_in_flag_should_be_priortized_over_env_and_config.stdout.golden
  tests/snapshots/TestCLICommands_Valid_log_level_in_env_should_be_priortized_over_config.stderr.golden
  tests/snapshots/TestCLICommands_Valid_log_level_in_flag_should_be_priortized_over_env_and_config.stderr.golden
  tests/test-cases/atmos-functions.yaml
  tests/test-cases/log-level-validation.yaml
Labels: patch, size/m

#1144 add terraform plan-diff command
  .cursor/rules/atmos-rules.mdc
  .github/workflows/test.yml
  Makefile
  cmd/terraform.go
  cmd/terraform_commands.go
  internal/exec/constants.go
  internal/exec/terraform.go
  internal/exec/terraform_plan_diff.go
  internal/exec/terraform_plan_diff_comparison.go
  internal/exec/terraform_plan_diff_comparison_test.go
  internal/exec/terraform_plan_diff_formatting.go
  internal/exec/terraform_plan_diff_formatting_test.go
  internal/exec/terraform_plan_diff_main_test.go
  internal/exec/terraform_plan_diff_preparation.go
  internal/exec/terraform_plan_diff_preparation_test.go
  internal/exec/terraform_plan_diff_test.go
  main.go
  main_hooks_and_store_integration_test.go
  main_plan_diff_integration_test.go
  pkg/errors/terraform_errors.go
  pkg/utils/log_utils.go
  pkg/utils/log_utils_test.go
  tests/fixtures/scenarios/plan-diff/atmos.yaml
  tests/fixtures/scenarios/plan-diff/components/terraform/mock/main.tf
  tests/fixtures/scenarios/plan-diff/stacks/deploy/nonprod.yaml
  tests/snapshots/TestCLICommands_atmos_terraform.stderr.golden
  tests/snapshots/TestCLICommands_atmos_terraform_--help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_terraform_--help_alias_subcommand_check.stdout.golden
  tests/snapshots/TestCLICommands_atmos_terraform_help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_terraform_non-existent.stderr.golden
  website/docs/cli/commands/terraform/terraform-plan-diff.mdx
  website/docs/cli/commands/terraform/usage.mdx
Labels: minor, needs-cloudposse, size/xl

#1167 suppress artifactory debug logging
  pkg/store/artifactory_store.go
  pkg/store/artifactory_store_noop_logger.go
  pkg/store/artifactory_store_noop_logger_test.go
  pkg/store/artifactory_store_test.go
Labels: patch, size/m

#1175 Fix bug related to loading and merging atmos configurations files
  pkg/config/config_test.go
  pkg/config/load.go
Labels: patch, size/s
