Repository cloudposse/atmos, pull requests merged in 2025-05, with the labels that each got.

#934 Support atmos docs generate feature natively
  atmos.yaml
  cmd/docs_generate.go
  go.mod
  go.sum
  internal/exec/docs_generate.go
  internal/exec/docs_generate_test.go
  internal/exec/error.go
  internal/exec/file_utils.go
  internal/exec/template_utils.go
  internal/exec/template_utils_test.go
  pkg/config/default.go
  pkg/config/load.go
  pkg/schema/schema.go
  tests/fixtures/scenarios/docs-generate/.gitignore
  tests/fixtures/scenarios/docs-generate/input-variants/README-local.yaml
  tests/fixtures/scenarios/docs-generate/input-variants/README.md.gotmpl
  tests/fixtures/scenarios/docs-generate/input-variants/atmos.yaml
  tests/fixtures/scenarios/docs-generate/readme/README.yaml
  tests/fixtures/scenarios/docs-generate/readme/atmos.yaml
  tests/fixtures/scenarios/docs-generate/terraform/README.md.gotmpl
  tests/fixtures/scenarios/docs-generate/terraform/README.yaml
  tests/fixtures/scenarios/docs-generate/terraform/atmos.yaml
  tests/fixtures/scenarios/docs-generate/terraform/context.tf
  tests/fixtures/scenarios/docs-generate/terraform/main.tf
  tests/fixtures/scenarios/docs-generate/terraform/outputs.tf
  tests/fixtures/scenarios/docs-generate/terraform/providers.tf
  tests/fixtures/scenarios/docs-generate/terraform/remote-state.tf
  tests/fixtures/scenarios/docs-generate/terraform/variables.tf
  tests/fixtures/scenarios/docs-generate/terraform/versions.tf
  tests/fixtures/scenarios/docs-generate/terraform/vpc-flow-logs.tf
  tests/snapshots/TestCLICommands_atmos_describe_config.stdout.golden
  tests/snapshots/TestCLICommands_atmos_describe_config_-f_yaml.stdout.golden
  tests/snapshots/TestCLICommands_atmos_describe_config_imports.stdout.golden
  tests/snapshots/TestCLICommands_atmos_describe_configuration.stdout.golden
  tests/snapshots/TestCLICommands_check_atmos_--help_in_empty-dir.stdout.golden
  tests/test-cases/docs-generate.yaml
  website/docs/cli/commands/docs/_category_.json
  website/docs/cli/commands/docs/docs-generate.mdx
  website/docs/cli/commands/docs/usage.mdx
Labels: enhancement, minor, size/xl

#1240 fix: Acceptance Tests Snapshots
  tests/snapshots/TestCLICommands_atmos_describe_config_imports.stdout.golden
Labels: no-release, size/s

#1227 Add no-color support for atmos
  atmos.yaml
  cmd/root.go
  cmd/root_test.go
  cmd/support_test.go
  cmd/validate_editorconfig.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/default.go
  pkg/config/load.go
  pkg/schema/schema.go
  pkg/ui/markdown/renderer.go
  pkg/ui/markdown/renderer_test.go
  tests/snapshots/TestCLICommands_Valid_Log_Level_in_Command_Line_Flag.stdout.golden
  tests/snapshots/TestCLICommands_Valid_Log_Level_in_Config_File.stdout.golden
  tests/snapshots/TestCLICommands_Valid_Log_Level_in_Environment_Variable.stdout.golden
  tests/snapshots/TestCLICommands_Valid_log_file_in_env_should_be_priortized_over_config.stdout.golden
  tests/snapshots/TestCLICommands_Valid_log_file_in_flag_should_be_priortized_over_env_and_config.stdout.golden
  tests/snapshots/TestCLICommands_Valid_log_level_in_env_should_be_priortized_over_config.stdout.golden
  tests/snapshots/TestCLICommands_Valid_log_level_in_flag_should_be_priortized_over_env_and_config.stdout.golden
  tests/snapshots/TestCLICommands_atmos_--help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_about_--help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_atlantis_--help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_atlantis_generate_--help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_atlantis_generate_help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_atlantis_generate_repo-config_--help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_atlantis_generate_repo-config_help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_atlantis_help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_describe_config.stdout.golden
  tests/snapshots/TestCLICommands_atmos_describe_config_-f_yaml.stdout.golden
  tests/snapshots/TestCLICommands_atmos_describe_config_imports.stdout.golden
  tests/snapshots/TestCLICommands_atmos_describe_configuration.stdout.golden
  tests/snapshots/TestCLICommands_atmos_helmfile_--help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_helmfile_apply_--help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_helmfile_apply_help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_helmfile_help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_support.stderr.golden
  tests/snapshots/TestCLICommands_atmos_support.stdout.golden
  tests/snapshots/TestCLICommands_atmos_terraform_--help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_terraform_--help_alias_subcommand_check.stdout.golden
  tests/snapshots/TestCLICommands_atmos_terraform_apply_--help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_terraform_apply_help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_terraform_help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_validate_editorconfig_--help.stdout.golden
  tests/snapshots/TestCLICommands_atmos_validate_editorconfig_help.stdout.golden
  tests/test-cases/empty-dir.yaml
  website/docs/cli/configuration/configuration.mdx
  website/docs/cli/configuration/markdown-styling.mdx
  website/docs/cli/configuration/terminal.mdx
Labels: minor, size/l

#1192 atmos list vendor
  cmd/list_vendor.go
  cmd/markdown/atmos_list_vendor_usage.md
  pkg/list/format/formatter.go
  pkg/list/format/table.go
  pkg/list/list_vendor.go
  pkg/list/list_vendor_format.go
  pkg/list/list_vendor_test.go
  pkg/schema/schema.go
  tests/snapshots/TestCLICommands_atmos_describe_config.stdout.golden
Labels: minor, size/xl

#1219 Custom Columns docs
  website/docs/cli/commands/list/list-components.mdx
  website/docs/cli/commands/list/list-metadata.mdx
  website/docs/cli/commands/list/list-settings.mdx
  website/docs/cli/commands/list/list-stacks.mdx
  website/docs/cli/commands/list/list-values.mdx
  website/docs/cli/commands/list/list-vars.mdx
  website/docs/cli/commands/list/list-workflows.mdx
  website/docs/cli/commands/list/usage.mdx
Labels: minor, needs-cloudposse, size/m

#1215 add pager for describe component
  Makefile
  cmd/describe.go
  cmd/describe_component.go
  internal/exec/atlantis_generate_repo_config.go
  internal/exec/atmos.go
  internal/exec/describe_affected.go
  internal/exec/describe_component.go
  internal/exec/describe_component_test.go
  internal/exec/describe_config.go
  internal/exec/describe_config_test.go
  internal/exec/describe_dependents.go
  internal/exec/describe_stacks.go
  internal/exec/describe_workflows.go
  internal/exec/file_utils.go
  pkg/atlantis/atlantis_generate_repo_config_test.go
  pkg/utils/highlight_utils.go
  pkg/utils/json_utils.go
  pkg/utils/json_utils_test.go
  pkg/utils/yaml_utils.go
  pkg/utils/yq_test.go
  tests/cli_describe_component_test.go
  tests/describe_test.go
  website/docs/cli/commands/describe/describe-component.mdx
Labels: minor, needs-cloudposse, size/l

#1180 Configure YAML formatting in atmos describe commands
  examples/demo-stacks/component.yaml
  internal/exec/describe_component.go
  internal/exec/describe_stacks.go
  internal/exec/file_utils.go
  internal/exec/file_utils_test.go
  internal/exec/filter_utils.go
  internal/exec/filter_utils_test.go
  internal/exec/helmfile.go
  internal/exec/helmfile_generate_varfile.go
  internal/exec/template_funcs_store_test.go
  internal/exec/terraform.go
  internal/exec/terraform_generate_varfile.go
  internal/exec/utils.go
  internal/exec/workflow_utils.go
  internal/exec/yaml_func_terraform_output_test.go
  pkg/describe/describe_stacks_test.go
  pkg/schema/schema.go
  pkg/schema/schema_test.go
  pkg/utils/yaml_test.go
  pkg/utils/yaml_utils.go
  tests/fixtures/scenarios/indentation/README.md
  tests/fixtures/scenarios/indentation/atmos.yaml
  tests/snapshots/TestCLICommands_atmos_describe_config.stdout.golden
  tests/snapshots/TestCLICommands_atmos_describe_config_-f_yaml.stdout.golden
  tests/snapshots/TestCLICommands_atmos_describe_config_imports.stdout.golden
  tests/snapshots/TestCLICommands_atmos_describe_configuration.stdout.golden
  tests/snapshots/TestCLICommands_atmos_stacks_with_relative_paths.stdout.golden
  tests/snapshots/TestCLICommands_indentation.stderr.golden
  tests/snapshots/TestCLICommands_indentation.stdout.golden
  tests/test-cases/indentation.yaml
  website/docs/cli/configuration/terminal.mdx
Labels: minor, size/xl

#1249 Fix: Bad characters when using the !include function
  pkg/filetype/filetype.go
  pkg/filetype/filetype_test.go
  pkg/utils/yaml_include_test.go
  pkg/utils/yaml_utils.go
  pkg/utils/yq_utils.go
  pkg/utils/yq_utils_test.go
Labels: minor, size/l
