Repository cloudposse/atmos, pull requests merged in 2025-01, with the labels that each got.

#898 feat: `TF_CLI_ARGS_*` Handling
  internal/exec/shell_utils.go
  internal/exec/terraform.go
Labels: minor

#874 add hooks and store write functionality
  cmd/terraform.go
  go.mod
  go.sum
  internal/exec/describe_stacks.go
  internal/exec/stack_processor_utils.go
  internal/exec/template_funcs_component.go
  internal/exec/terraform.go
  internal/exec/terraform_generate_backends.go
  internal/exec/terraform_outputs.go
  internal/exec/terraform_utils.go
  internal/exec/utils.go
  internal/exec/yaml_func_store.go
  internal/exec/yaml_func_terraform_output.go
  pkg/config/const.go
  pkg/hooks/hooks.go
  pkg/hooks/store.go
  pkg/store/aws_ssm_param_store.go
  pkg/store/aws_ssm_param_store_test.go
  pkg/store/in_memory_store.go
  pkg/store/in_memory_store_test.go
  pkg/store/registry.go
  pkg/store/store.go
Labels: no-release

#922 feat: Test Cases as a Directory
  tests/cli_test.go
  tests/fixtures/components/terraform/.gitkeep
  tests/test-cases/complete.yaml
Labels: no-release

#891 feat: Support Relative Path Imports
  .gitignore
  examples/demo-context/stacks/deploy/dev/demo.yaml
  examples/demo-context/stacks/deploy/prod/demo.yaml
  examples/demo-context/stacks/deploy/staging/demo.yaml
  internal/exec/stack_processor_utils.go
  pkg/stack/stack_processor_test.go
  tests/fixtures/scenarios/relative-paths/atmos.yaml
  tests/fixtures/scenarios/relative-paths/components/terraform/myapp/README.md
  tests/fixtures/scenarios/relative-paths/components/terraform/myapp/main.tf
  tests/fixtures/scenarios/relative-paths/components/terraform/myapp/outputs.tf
  tests/fixtures/scenarios/relative-paths/components/terraform/myapp/variables.tf
  tests/fixtures/scenarios/relative-paths/components/terraform/myapp/versions.tf
  tests/fixtures/scenarios/relative-paths/stacks/catalog/myapp.yaml
  tests/fixtures/scenarios/relative-paths/stacks/orgs/acme/_defaults.yaml
  tests/fixtures/scenarios/relative-paths/stacks/orgs/acme/platform/_defaults.yaml
  tests/fixtures/scenarios/relative-paths/stacks/orgs/acme/platform/dev.yaml
  tests/fixtures/scenarios/relative-paths/stacks/orgs/acme/platform/prod.yaml
  tests/fixtures/scenarios/relative-paths/stacks/orgs/acme/platform/staging.yaml
  tests/test-cases/relative-paths.yaml
Labels: minor

#929 Prevent normalization of binaries and whitespace sensitive files
  .gitattributes
Labels: no-release, needs-cloudposse

#924 chore: Separate Test Cases
  tests/test-cases/complete.yaml
  tests/test-cases/core.yaml
  tests/test-cases/demo-custom-command.yaml
  tests/test-cases/demo-stacks.yaml
Labels: no-release

#931 Tweak `.gitattributes`
  .gitattributes
Labels: no-release

#921 add artifactory store
  cmd/terraform.go
  go.mod
  go.sum
  internal/exec/terraform.go
  pkg/hooks/cmd.go
  pkg/store/artifactory_store.go
  pkg/store/artifactory_store_test.go
  pkg/store/registry.go
Labels: no-release

#961 update website release workflow trigger on releases
  .github/workflows/website-deploy-prod.yml
Labels: no-release, needs-cloudposse

#964 Fix typo Atoms -> Atmos
  website/docs/quick-start/advanced/configure-cli.mdx
Labels: no-release

#965 Fix typo stage 4 -> stage 3
  website/docs/introduction/why-atmos/stage-3.mdx
Labels: no-release

#967 Remove Broken Link to Schema
  website/docs/cli/schemas.mdx
Labels: no-release

#993 Disable Build Harness
  Makefile
Labels: no-release, needs-cloudposse

#991 ci: format Go code by autofix.ci
  .github/workflows/autofix.yml
  .github/workflows/test.yml
  aqua/aqua-checksums.json
  aqua/aqua.yaml
  aqua/imports/gofumpt.yaml
Labels: no-release, needs-cloudposse
