Repository cloudposse/atmos, pull requests merged in 2025-04, with the labels that each got.

#1178 Add golangci-lint rule to deprecate the `processArgsAndFlags` function
  .golangci.yml
  internal/exec/utils.go
Labels: no-release, size/xs

#1183 Replace refs to "master" branch, fix "!store" doc formatting
  website/docs/cli/commands/validate/validate-stacks.mdx
  website/docs/cli/versioning.mdx
  website/docs/core-concepts/components/components.mdx
  website/docs/core-concepts/share-data/remote-state.mdx
  website/docs/core-concepts/stacks/yaml-functions/store.mdx
  website/docs/core-concepts/validate/json-schema.mdx
  website/docs/core-concepts/validate/opa.mdx
  website/docs/core-concepts/validate/validate.mdx
  website/docs/quick-start/advanced/configure-repository.md
  website/docs/quick-start/advanced/configure-validation.mdx
  website/docs/quick-start/advanced/vendor-components.mdx
  website/docs/tutorials/atmos-example-infra.mdx
  website/docusaurus.config.js
Labels: documentation, no-release, size/s

#990 feat(DEV-2781): Notify Not Running in a Git Repo
  cmd/cmd_utils.go
  cmd/cmd_utils_test.go
  tests/snapshots/TestCLICommands_atmos_doesnt_warn_if_in_git_repo_with_atmos_config.stderr.golden
  tests/snapshots/TestCLICommands_atmos_doesnt_warn_if_in_git_repo_with_atmos_config.stdout.golden
  tests/snapshots/TestCLICommands_atmos_doesnt_warn_if_in_git_repo_with_no_atmos_config.stderr.golden
  tests/snapshots/TestCLICommands_atmos_doesnt_warn_if_in_git_repo_with_no_atmos_config.stdout.golden
  tests/snapshots/TestCLICommands_atmos_doesnt_warn_if_not_in_git_repo_with_atmos_config.stderr.golden
  tests/snapshots/TestCLICommands_atmos_doesnt_warn_if_not_in_git_repo_with_atmos_config.stdout.golden
  tests/snapshots/TestCLICommands_atmos_warns_if_not_in_git_repo_with_no_atmos_config.stderr.golden
  tests/snapshots/TestCLICommands_atmos_warns_if_not_in_git_repo_with_no_atmos_config.stdout.golden
  tests/test-cases/empty-dir.yaml
Labels: minor, size/m

#1212 chore: Log Level for TTY Warning
  internal/exec/vendor_model.go
  tests/snapshots/TestCLICommands_atmos_vendor_pull_(no_tty).stderr.golden
  tests/snapshots/TestCLICommands_atmos_vendor_pull_(no_tty).stdout.golden
  tests/snapshots/TestCLICommands_atmos_vendor_pull_component_using_SSH.stderr.golden
  tests/snapshots/TestCLICommands_atmos_vendor_pull_custom_detector_credentials_leakage.stderr.golden
  tests/snapshots/TestCLICommands_atmos_vendor_pull_ssh.stderr.golden
  tests/snapshots/TestCLICommands_atmos_vendor_pull_using_SSH.stderr.golden
  tests/snapshots/TestCLICommands_atmos_vendor_pull_with_custom_detector_and_handling_credentials_leakage.stderr.golden
  tests/test-cases/demo-vendoring.yaml
Labels: patch, size/s

#1211 DEV-2179: Component Updater Docs
  website/docs/integrations/github-actions/component-updater.mdx
  website/src/components/Step/index.css
Labels: documentation, no-release, size/s
